### ISSUE TITLE
Branch And Bound Wallet could be improved not to explore fruitless branches

### ISSUE THREAD

**Issue by murchandamus** [Xekyo/CoinSelectionSimulator#1]
Branch and Bound will explore branches until they exceed the target or until a leaf is reached (or the global cut-off is reached).
BnB could be more efficient if a "Lookahead" were added that informs about the total a branch to the leaf may still yield. Branches that cannot reach sufficient payload to fund the target could then be cut off early to explore more promising branches.

**Comment by karelbilek** [comment]
This is already implemented, right?

**Comment by murchandamus** [comment]
Correct! You can find it in https://github.com/Xekyo/CoinSelectionSimulator/blob/master/src/main/scala/one/murch/bitcoin/coinselection/StackEfficientTailRecursiveBnB.scala
